# Add new issues to the correct project
name: '.Platform: Assign Issue to Project'

on:
  workflow_dispatch:
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-to-project:
    name: Add Issues to Projects
    runs-on: ubuntu-latest
    steps:
      - name: 'Add Bug to Bug Board'
        env:
          GITHUB_TOKEN: ${{ secrets.PLATFORM_PROJECT_TOKEN }}
        if: |
          contains(github.event.issue.labels.*.name, 'bug')
        shell: pwsh
        run: |
          $project = gh api graphql -f query='
            query($organization: String! $number: Int!){
              organization(login: $organization){
                projectV2(number: $number) {
                  id
                }
              }
            }' -f organization="Azure" -F number=364 | ConvertFrom-Json -Depth 10

          $bugBoardId = $project.data.organization.projectV2.id

          gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
                item {
                  id
                }
              }
            }' -f project=$bugBoardId -f issue=${{ github.event.issue.node_id }} --jq '.data.addProjectV2ItemById.projectV2Item.id'
      - name: 'Add Issues to Backlog Board'
        env:
          GITHUB_TOKEN: ${{ secrets.PLATFORM_PROJECT_TOKEN }}
        if: |
          contains(github.event.issue.labels.*.name, 'enhancement')
        shell: pwsh
        run: |
          $project = gh api graphql -f query='
            query($organization: String! $number: Int!){
              organization(login: $organization){
                projectV2(number: $number) {
                  id
                }
              }
            }' -f organization="Azure" -F number=363 | ConvertFrom-Json -Depth 10

          $backlogId = $project.data.organization.projectV2.id

          gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
                item {
                  id
                }
              }
            }' -f project=$backlogId -f issue=${{ github.event.issue.node_id }} --jq '.data.addProjectV2ItemById.projectV2Item.id'
